### PR TITLE
Tidy gitignore

### PR DESCRIPTION
**Pull request by astavale**
A common workflow is to do `git status` before `git add`. This series of patches tidies up `.gitignore` so `git status` shows only the modified files that need to be committed. At the moment `git status` shows a lot of automatically generated files that do not need to be under version control.

### CODE REVIEW

**Comment by chebizarro** [comment]
Gherkin for Vala uses the gtk.mk automake script to compile the .gitignore file every time make is run, so any manual changes like this would be overwritten. The problem was that I added git.mk after several builds so it automatically ignores anything per-existing. The solution is to purge the working directory of any build files and rebuild it which should update the .gitignore file. I'm circling back around to Valadate and Gherkin in the next couple of days now I have some free time again to clean up the source tree and fix some bugs.

**Comment by astavale** [comment]
I'm not sure this is working. When I use `make ` my version of .gitignore remains the same. This is the same when I do ./autogen.sh again.

It may be worth switching to using a separate build directory, so the .gitignore file is made much simpler and can be handled manually. See [Why you should consider using separate build directories](http://voices.canonical.com/jussi.pakkanen/2013/04/16/why-you-should-consider-using-separate-build-directories/) for a good summary of the advantages.

At present the following kind of works:
```
cd gherkin-vala
mkdir x86_64
cd x86_64
../autogen.sh
make
```
It would be good if there was a way for `autogen.sh` to choose a default build directory, such as `build` or `obj` if $PWD is the same as source directory.

Use of VPATH seems important when using separate build directories:
 * [4.8.4 Build Directories](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Build-Directories.html) - "To support doing this, make uses the VPATH variable to find the files that are in the source directory...If you are using GNU Automake, the remaining details in this section are already covered for you, based on the contents of your Makefile.am."
 * [Multi-Architecture Builds](http://make.mad-scientist.net/papers/multi-architecture-builds/) - "The most popular example of this method are the build environments created with a combination of GNU autoconf and GNU automake. There, the configure script is run from a remote directory and it sets things up for you in that remote directory without modifying the original sources. Then you run a VPATH-capable make, such as GNU make, and it uses VPATH to locate the source files in the distribution directory, while writing the target files in the directory where you invoked the build..."
 * [Writing a large build system with GNU make](http://david.rothlis.net/large-gnu-make/) - "Automake and CMake both allow the user to choose a build directory separate from the source directory. This allows you to build separate “debug” and “release” versions from the same source directory, or to cross-compile to several different targets, without the builds trampling on each other. GNU make’s solution is VPATH."

Getting this to work on a Vala project would be a good example for fixing [Bug 725497 - Makefile.am: Use builddir correctly instead of srcdir](https://bugzilla.gnome.org/show_bug.cgi?id=725497) in Vala itself.

**Comment by chebizarro** [comment]
Thanks for the info, I'm planning to integrate Valadate for unit testing early next week so I'll be completely revising the Makefile and will set up a separate build directory as you suggest. This should also fix the problem with the .gitignore which I'd prefer to leave in place for now.

**Comment by astavale** [comment]
Just a note that autom4te.cache/traces.1 and autom4te.cache/traces.2  should also be removed from version control. At present these filings are making gherkin-vala show as a Groof project: https://github.com/chebizarro/gherkin-vala/search?l=groff

**Pull request closed without merging**
